[package]
name = "disquip-bot"
version = "0.8.1"
edition = "2024"
description = "A Discord bot to play audio files (quips) on command"
documentation = "https://github.com/blthayer/disquip-bot-rs/blob/main/README.md"
readme = "README.md"
repository = "https://github.com/blthayer/disquip-bot-rs"
homepage = "https://github.com/blthayer/disquip-bot-rs"
license = "MIT"
keywords = ["discord", "audio", "bot", "soundboard", "civ"]
categories = ["games", "multimedia::audio"]

[package.metadata.deb]
maintainer = "Brandon Thayer <bthayer@tuta.com>"
copyright = "2025, Brandon Thayer <bthayer@tuta.com>"
license-file = ["LICENSE", "4"]
extended-description = """\
A Discord bot to play audio files (quips) on command.
Users enter commands into a Discord text channel in a server in which the bot has been added/registered.
Additionally includes randomization features for Civilization VI game setup.
"""
depends = "$auto"
section = "sound"
priority = "optional"
maintainer-scripts = "systemd/"
systemd-units = [{ unit-name = "disquip-bot", enable = true, start = true }]

[dependencies]
rand = { version = "0.10", default-features = false, features = ["thread_rng"] }
# For the serenity-rs stack, mostly just yoinking their default features.
serenity = {version = "0.12", default-features = false, features = ["default_no_backend", "rustls_backend", "voice"] }
poise = { version = "0.6", default-features = false, features = ["cache", "chrono", "handle_panics"] }
# builtin-queue in addition to defaults:
songbird = { version = "0.6", default-features = false, features = ["driver", "gateway", "rustls", "serenity", "tungstenite", "builtin-queue"] }
# Tried symphonia 0.6 on 2026-05-16, no luck. Songbird is probably not yet compatible.
# https://github.com/pdeljanov/Symphonia/blob/main/docs/guides/migration/0p6.md
# Currently just supporting mp3 and wav, could add future feature support to
# toglle more features.
symphonia = { version = "0.5", default-features = false, features = ["wav", "mp3"] }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }
ahash = { version = "0.8", default-features = false, features = ["runtime-rng", "std"] }

[features]
default = []
# Enables game setup randomization commands for Civilization VI.
civ = []

[profile.release]
lto = "fat"
codegen-units = 1

[lints.clippy]
# correctness, suspicious, style, complexity, perf
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
